version: "3"



#
# Descrição dos serviços
services:


  #
  # Servidor Web
  web-server:
    container_name: dev-php-webserver
    image: aeondigital/apache-php-7.4:dev
    volumes:
      #
      # Diretórios de arquivos de configuração.
      # Apache
      - ./container-config/apache-php-7.4/etc/apache2/sites-available:/etc/apache2/sites-available
      - ./container-config/apache-php-7.4/etc/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./container-config/apache-php-7.4/etc/apache2/envvars:/etc/apache2/envvars
      # PHP
      - ./container-config/apache-php-7.4/etc/php/7.4/apache2/php.ini:/etc/php/7.4/apache2/php.ini
      - ./container-config/apache-php-7.4/etc/php/7.4/cli/php.ini:/etc/php/7.4/cli/php.ini
      # Variáveis de ambiente
      - ./container-config/apache-php-7.4/etc/.env:/etc/.env
      #
      # Aplicação
      - ./src:/var/www/html
    ports:
      - 8080:80
    links:
      - db-server

  #
  # Servidor de banco de dados
  db-server:
    container_name: dev-php-dbserver
    image: aeondigital/mysql-8.0:dev
    volumes:
      #
      # Diretórios de arquivos de configuração.
      # MySql
      - ./container-config/mysql-8.0/etc/mysql:/etc/mysql
